name: Run tests
on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    strategy:
      matrix:
        versions:
          # Django 3.2
          - django: "3.2.*"
            python: "3.7"
          - django: "3.2.*"
            python: "3.8"
          - django: "3.2.*"
            python: "3.9"
          - django: "3.2.*"
            python: "3.10"
          # Django 4.0
          - django: "4.0.*"
            python: "3.8"
          - django: "4.0.*"
            python: "3.9"
          - django: "4.0.*"
            python: "3.10"
          # Django 4.1
          - django: "4.1.*"
            python: "3.8"
          - django: "4.1.*"
            python: "3.9"
          - django: "4.1.*"
            python: "3.10"
          - django: "4.1.*"
            python: "3.11"
          # Django 4.2
          - django: "4.2.*"
            python: "3.8"
          - django: "4.2.*"
            python: "3.9"
          - django: "4.2.*"
            python: "3.10"
          - django: "4.2.*"
            python: "3.11"
          # Django 5.0
          - django: "5.0.*"
            python: "3.10"
          - django: "5.0.*"
            python: "3.11"
          - django: "5.0.*"
            python: "3.12"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python version ${{ matrix.versions.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.versions.python }}
      - name: Install poetry
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry
      
      - name: Set up dependencies
        run: python -m poetry install
      - name: Re-install specific Django version
        run: pip install Django=="${{ matrix.versions.django }}"
      - name: Run tests
        run: python example/manage.py test
  
  lint:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install poetry
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry
      
      - name: Set up dependencies
        run: python -m poetry install
      - name: Run black
        run: black --check --diff lb_health_check/
