name: Run tests
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        django-version:
          - 2.2.*
          - 3.0.*
          - 3.1.*
          - 3.2.*
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry ${{ matrix.poetry-version }}
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry
      
      - name: Set up dependencies
        run: python -m poetry install
      - run: pip install Django=="${{ matrix.django-version }}"
      - run: python example/manage.py test

